version: '3.7'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV-development}
    env_file: .env
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV-development}
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules

volumes:
  node_modules:
