connections:
  main:
    host: screeps.com
    secure: true
    token: <your-auth-token>
    username: <your-username>
  ptr:
    host: screeps.com/ptr
    secure: true
    token: <your-auth-token>
    username: <your-username>
max_history: 200000
max_scroll: 200000
smooth_scroll: true
