export enum CODES {
    OK = 1,

    ERROR = 100,

    ERROR_SPAWN_NOT_FOUND = 101,
    ERROR_CANT_FIND_PROCESS = 102,
    ERROR_PARENT_PROCESS_DIED = 103,
    ERROR_MISSING_METHOD_IMPLEMENTATION = 104
}

export enum PRIORITY {
    VERY_HIGH = 5,
    HIGH = 4,
    NORMAL = 3,
    LOW = 2,
    VERY_LOW = 1
}

export enum MISSIONS {
    COLLECT_ENERGY,
    CONTAINER,
    FIND_ENERGY_TARGET,
    FIND_TRANSFER_TARGET,
    GET_ENERGY,
    HARVESTER,
    MOVE_TO_ENERGY_TARGET,
    MOVE_TO_TRANSFER_TARGET,
    MOVING_TO_SOURCE,
    TRANSFER_ENERGY,
    MOVE_TO_CONTROLLER,
    UPGRADE_CONTROLLER,
    FIND_BUILD_TARGET,
    CONSTRUCT,
}

export const DEBUG = {
    SPAWN: true
}
