version: "3.7"

services:
  screeps_console:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/opt/app/src
      - ./requirements.txt:/opt/app/requirements.txt
      - ./.screepsconsole.yaml:/root/.screepsconsole.yaml
